import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { MatTab, MatTabGroup } from '@angular/material/tabs';
import { MatFormField, MatLabel, MatSuffix } from '@angular/material/form-field';
import { MatOption, MatSelect } from '@angular/material/select';
import { MatInput } from '@angular/material/input';
import { MatIcon } from '@angular/material/icon';
import { MatIconButton } from '@angular/material/button';
import { FormsModule } from '@angular/forms';
import { Language } from '../model/language';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, MatTab, MatTabGroup, MatFormField, MatLabel,
    MatSelect, MatOption, MatInput, MatSuffix, MatIcon, MatIconButton, FormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'frontend';

  languages: Language[] = [
    { value: 'af', viewValue: 'afrykański' },
    { value: 'sq', viewValue: 'albański' },
    { value: 'am', viewValue: 'amharski' },
    { value: 'ar', viewValue: 'arabski' },
    { value: 'hy', viewValue: 'ormiański' },
    { value: 'as', viewValue: 'asamski' },
    { value: 'ay', viewValue: 'ajmara' },
    { value: 'az', viewValue: 'azerski' },
    { value: 'bm', viewValue: 'bambara' },
    { value: 'eu', viewValue: 'baskijski' },
    { value: 'be', viewValue: 'białoruski' },
    { value: 'bn', viewValue: 'bengalski' },
    { value: 'bho', viewValue: 'bhojpuri' },
    { value: 'bs', viewValue: 'bośniacki' },
    { value: 'bg', viewValue: 'bułgarski' },
    { value: 'ca', viewValue: 'kataloński' },
    { value: 'ceb', viewValue: 'cebuański' },
    { value: 'zh-CN', viewValue: 'chiński (uproszczony)' },
    { value: 'zh-TW', viewValue: 'chiński (tradycyjny)' },
    { value: 'co', viewValue: 'korsykański' },
    { value: 'hr', viewValue: 'chorwacki' },
    { value: 'cs', viewValue: 'czeski' },
    { value: 'da', viewValue: 'duński' },
    { value: 'dv', viewValue: 'malediwski (dhivehi)' },
    { value: 'doi', viewValue: 'dogri' },
    { value: 'nl', viewValue: 'niderlandzki' },
    { value: 'en', viewValue: 'angielski' },
    { value: 'eo', viewValue: 'esperanto' },
    { value: 'et', viewValue: 'estoński' },
    { value: 'ee', viewValue: 'ewe' },
    { value: 'fil', viewValue: 'filipiński (tagalog)' },
    { value: 'fi', viewValue: 'fiński' },
    { value: 'fr', viewValue: 'francuski' },
    { value: 'fy', viewValue: 'fryzyjski' },
    { value: 'gl', viewValue: 'galicyjski' },
    { value: 'ka', viewValue: 'gruziński' },
    { value: 'de', viewValue: 'niemiecki' },
    { value: 'el', viewValue: 'grecki' },
    { value: 'gn', viewValue: 'guarani' },
    { value: 'gu', viewValue: 'gudżarati' },
    { value: 'ht', viewValue: 'kreolski haitański' },
    { value: 'ha', viewValue: 'hausa' },
    { value: 'haw', viewValue: 'hawajski' },
    { value: 'he', viewValue: 'hebrajski' },
    { value: 'hi', viewValue: 'hindi' },
    { value: 'hmn', viewValue: 'hmong' },
    { value: 'hu', viewValue: 'węgierski' },
    { value: 'is', viewValue: 'islandzki' },
    { value: 'ig', viewValue: 'igbo' },
    { value: 'ilo', viewValue: 'ilocano' },
    { value: 'id', viewValue: 'indonezyjski' },
    { value: 'ga', viewValue: 'irlandzki' },
    { value: 'it', viewValue: 'włoski' },
    { value: 'ja', viewValue: 'japoński' },
    { value: 'jv', viewValue: 'jawajski' },
    { value: 'kn', viewValue: 'kanada' },
    { value: 'kk', viewValue: 'kazachski' },
    { value: 'km', viewValue: 'khmerski' },
    { value: 'rw', viewValue: 'kinyarwanda' },
    { value: 'gom', viewValue: 'konkani' },
    { value: 'ko', viewValue: 'koreański' },
    { value: 'kri', viewValue: 'krio' },
    { value: 'ku', viewValue: 'kurdyjski' },
    { value: 'ckb', viewValue: 'kurdyjski (sorani)' },
    { value: 'ky', viewValue: 'kirgiski' },
    { value: 'lo', viewValue: 'laotański' },
    { value: 'la', viewValue: 'łaciński' },
    { value: 'lv', viewValue: 'łotewski' },
    { value: 'ln', viewValue: 'lingala' },
    { value: 'lt', viewValue: 'litewski' },
    { value: 'lg', viewValue: 'luganda' },
    { value: 'lb', viewValue: 'luksemburski' },
    { value: 'mk', viewValue: 'macedoński' },
    { value: 'mai', viewValue: 'maithili' },
    { value: 'mg', viewValue: 'malgaski' },
    { value: 'ms', viewValue: 'malajski' },
    { value: 'ml', viewValue: 'malajalam' },
    { value: 'mt', viewValue: 'maltański' },
    { value: 'mi', viewValue: 'maoryski' },
    { value: 'mr', viewValue: 'marathi' },
    { value: 'mni-Mtei', viewValue: 'meiteilon (manipuri)' },
    { value: 'lus', viewValue: 'mizo' },
    { value: 'mn', viewValue: 'mongolski' },
    { value: 'my', viewValue: 'birmański' },
    { value: 'ne', viewValue: 'nepalski' },
    { value: 'no', viewValue: 'norweski' },
    { value: 'ny', viewValue: 'nyanja (chichewa)' },
    { value: 'or', viewValue: 'odia (oriya)' },
    { value: 'om', viewValue: 'oromski' },
    { value: 'ps', viewValue: 'paszto' },
    { value: 'fa', viewValue: 'perski' },
    { value: 'pl', viewValue: 'polski' },
    { value: 'pt', viewValue: 'portugalski (portugalia, brazylia)' },
    { value: 'pa', viewValue: 'pendżabski' },
    { value: 'qu', viewValue: 'keczua' },
    { value: 'ro', viewValue: 'rumuński' },
    { value: 'ru', viewValue: 'rosyjski' },
    { value: 'sm', viewValue: 'samoański' },
    { value: 'sa', viewValue: 'sanskryt' },
    { value: 'gd', viewValue: 'szkocki gaelicki' },
    { value: 'nso', viewValue: 'sepedi' },
    { value: 'sr', viewValue: 'serbski' },
    { value: 'st', viewValue: 'sotho' },
    { value: 'sn', viewValue: 'szona' },
    { value: 'sd', viewValue: 'sindhi' },
    { value: 'si', viewValue: 'syngaleski' },
    { value: 'sk', viewValue: 'słowacki' },
    { value: 'sl', viewValue: 'słoweński' },
    { value: 'so', viewValue: 'somalijski' },
    { value: 'es', viewValue: 'hiszpański' },
    { value: 'su', viewValue: 'sundajski' },
    { value: 'sw', viewValue: 'suahili' },
    { value: 'sv', viewValue: 'szwedzki' },
    { value: 'tl', viewValue: 'tagalog (filipiński)' },
    { value: 'tg', viewValue: 'tadżycki' },
    { value: 'ta', viewValue: 'tamilski' },
    { value: 'tt', viewValue: 'tatarski' },
    { value: 'te', viewValue: 'telugu' },
    { value: 'th', viewValue: 'tajski' },
    { value: 'ti', viewValue: 'tigrinia' },
    { value: 'ts', viewValue: 'tsonga' },
    { value: 'tr', viewValue: 'turecki' },
    { value: 'tk', viewValue: 'turkmeński' },
    { value: 'ak', viewValue: 'twi (akan)' },
    { value: 'uk', viewValue: 'ukraiński' },
    { value: 'ur', viewValue: 'urdu' },
    { value: 'ug', viewValue: 'ujgurski' },
    { value: 'uz', viewValue: 'uzbecki' },
    { value: 'vi', viewValue: 'wietnamski' },
    { value: 'cy', viewValue: 'walijski' },
    { value: 'xh', viewValue: 'xhosa' },
    { value: 'yi', viewValue: 'jidysz' },
    { value: 'yo', viewValue: 'joruba' },
    { value: 'zu', viewValue: 'zulu' },
  ];
}
