fail_fast: true
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: versionbump
        name: Bump version hook
        entry: ./scripts/pre-commit
        language: system
        pass_filenames: false

