plugins {
    id "java"
    id "groovy"
    id "com.gradleup.shadow"
    id "io.micronaut.application"
    id "io.micronaut.aot"
    id "org.owasp.dependencycheck"
    id "com.andrzejpiontek.version-bump"
    id "org.ajoberstar.grgit"
}

version = "0.52.6"
group = "com.poliglotek"

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    // micronaut
    implementation platform("io.micronaut:micronaut-bom:3.10.4")
    implementation "io.micronaut.serde:micronaut-serde-jackson"
    implementation "io.micronaut.validation:micronaut-validation"
    implementation "io.micronaut:micronaut-http-client"
    implementation "io.micronaut.security:micronaut-security-oauth2"
    implementation "io.micronaut.security:micronaut-security-jwt"
    implementation "io.micronaut.gcp:micronaut-gcp-common"
    implementation "io.micronaut.gcp:micronaut-gcp-logging" // google cloud logging support
    implementation "io.micronaut.cache:micronaut-cache-core"
    implementation "io.micronaut.cache:micronaut-cache-caffeine"
    annotationProcessor "io.micronaut.validation:micronaut-validation-processor"
    annotationProcessor "io.micronaut.serde:micronaut-serde-processor"
    annotationProcessor "io.micronaut:micronaut-http-validation"
    testImplementation "io.micronaut:micronaut-http-client"

    // google
    implementation "com.google.api-client:google-api-client:_"
    implementation "com.google.cloud:google-cloud-firestore:_"
    implementation "com.google.cloud:google-cloud-translate:_"

    // logging
    implementation "ch.qos.logback:logback-classic:_"
    implementation "org.fusesource.jansi:jansi:_" // coloured console output

    // web scraping
    implementation "org.jsoup:jsoup:_" // static pages
    implementation "org.seleniumhq.selenium:selenium-java:_" // dynamic pages

    // testing
    testImplementation "net.bytebuddy:byte-buddy:_" // to mock classes and generate mock implementations
    testImplementation "org.objenesis:objenesis:_" // to mock classes without default constructors

    implementation "org.yaml:snakeyaml:_"
//    implementation "com.mailgun:mailgun-java:_"
}

application {
    mainClass = "com.poliglotek.Application"
}

java {
    sourceCompatibility = JavaVersion.toVersion("21")
    targetCompatibility = JavaVersion.toVersion("21")
}

micronaut {
    runtime "netty"
    testRuntime "spock2"
    processing {
        incremental true
        annotations "com.poliglotek.*"
    }
    aot {
        // https://micronaut-projects.github.io/micronaut-aot/latest/guide/
        optimizeServiceLoading = false
        convertYamlToJava = false
        precomputeOperations = true
        cacheEnvironment = true
        optimizeClassLoading = true
        deduceEnvironment = true
        optimizeNetty = true
        replaceLogbackXml = true
    }
}

dependencyCheck {
    nvd.apiKey = System.getenv("nvdApiKey")
}

tasks.register("installGitHook", Copy) {
    from new File(rootProject.rootDir, "scripts/pre-commit")
    into { new File(rootProject.rootDir, ".git/hooks") }
    filePermissions {
        user {
            read = true
            write = true
            execute = true
        }
        group {
            read = true
            write = false
            execute = true
        }
        other {
            read = true
            write = false
            execute = true
        }
    }
}

tasks.named("compileJava") {
    dependsOn installGitHook
}

versionBump{ }

tasks.register("buildFrontend", Exec) {
    def environment = System.getenv("MICRONAUT_ENVIRONMENTS")
    workingDir "src/frontend"
    if (environment == "dev") {
        println("Building front-end for dev environment")
        commandLine "npm", "run", "build-dev"
    } else {
        println("Building front-end for prod environment")
        commandLine "npm", "run", "build-prod"
    }
}

tasks.register("copyFrontend", Copy) {
    dependsOn buildFrontend
    from "src/frontend/dist/frontend"
    into "src/main/resources/public"
}

tasks.named("copyFrontend") {
    outputs.dir("src/main/resources/public")
}

tasks.named("processResources") {
    dependsOn copyFrontend
}

tasks.named("classes") {
    dependsOn copyFrontend
}

tasks.named("inspectRuntimeClasspath") {
    dependsOn copyFrontend
}

tasks.withType(Test).configureEach {
    enabled = false // if set to `false` will exclude tests when running build
}

build.dependsOn copyFrontend
