plugins {
    id "java"
    id "groovy"
    id "com.github.johnrengelman.shadow" version "8.1.1"
    id "io.micronaut.application" version "4.4.4"
    id "io.micronaut.aot" version "4.4.4"
    id "org.owasp.dependencycheck" version "10.0.4"
    id "com.andrzejpiontek.version-bump" version "0.0.2"
    id "org.ajoberstar.grgit" version "5.0.0-rc.3"
}

version = "0.48.54"
group = "com.poliglotek"

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    // micronaut
    annotationProcessor "io.micronaut.validation:micronaut-validation-processor"
    annotationProcessor "io.micronaut.serde:micronaut-serde-processor"
    annotationProcessor "io.micronaut:micronaut-http-validation"
    implementation "io.micronaut.serde:micronaut-serde-jackson"
    implementation "io.micronaut.validation:micronaut-validation"
    implementation "io.micronaut:micronaut-http-client"
    testImplementation "io.micronaut:micronaut-http-client"

    // lombok
    annotationProcessor "org.projectlombok:lombok:1.18.34"
    testAnnotationProcessor "org.projectlombok:lombok:1.18.34"
    implementation "org.projectlombok:lombok:1.18.34"
    testCompileOnly "org.projectlombok:lombok:1.18.34"

    // jsoup
    implementation "org.jsoup:jsoup:1.18.1"

    // selenium
    implementation "org.seleniumhq.selenium:selenium-java:4.27.0"

    // google cloud
    implementation "com.google.cloud:google-cloud-translate:2.52.0"

    // snakeyaml
    implementation "org.yaml:snakeyaml:2.0"

    // mailgun
    implementation "com.mailgun:mailgun-java:1.1.3"

    // logback
    implementation "ch.qos.logback:logback-classic"

    // byte buddy - used by spock to mock classes and generate mock implementations
    testImplementation "net.bytebuddy:byte-buddy:1.14.9"

    // objenesis - used by spock to mock classes without default constructors
    testImplementation "org.objenesis:objenesis:3.4"
}

application {
    mainClass = "com.poliglotek.Application"
}

java {
    sourceCompatibility = JavaVersion.toVersion("21")
    targetCompatibility = JavaVersion.toVersion("21")
}

micronaut {
    runtime "netty"
    testRuntime "spock2"
    processing {
        incremental true
        annotations "com.poliglotek.*"
    }
    aot {
        // https://micronaut-projects.github.io/micronaut-aot/latest/guide/
        optimizeServiceLoading = false
        convertYamlToJava = false
        precomputeOperations = true
        cacheEnvironment = true
        optimizeClassLoading = true
        deduceEnvironment = true
        optimizeNetty = true
        replaceLogbackXml = true
    }
}

dependencyCheck {
    nvd {
        apiKey = System.getenv("nvdApiKey")
    }
}

tasks.register("installGitHook", Copy) {
    from new File(rootProject.rootDir, "scripts/pre-commit")
    into { new File(rootProject.rootDir, ".git/hooks") }
    fileMode 0755
}

tasks.named("compileJava") {
    dependsOn installGitHook
}

versionBump{ }

tasks.register("buildFrontend", Exec) {
    def frontEndEnv = project.hasProperty("frontEndEnv") ? project.getProperty("frontEndEnv") : "prod"
    workingDir "src/frontend"
    if (frontEndEnv == "dev") {
        commandLine "npm", "run", "build-dev"
    } else {
        commandLine "npm", "run", "build-prod"
    }
}

tasks.register("copyFrontend", Copy) {
    dependsOn buildFrontend
    from "src/frontend/dist/frontend"
    into "src/main/resources/public"
}

tasks.named("copyFrontend") {
    outputs.dir("src/main/resources/public")
}

tasks.named("processResources") {
    dependsOn copyFrontend
}

tasks.named("classes") {
    dependsOn copyFrontend
}

tasks.named("inspectRuntimeClasspath") {
    dependsOn copyFrontend
}

tasks.withType(Test).configureEach {// Excludes tests when running build
    enabled = false
}

build.dependsOn copyFrontend
