plugins {
    id "java"
    id "groovy"
    id "com.github.johnrengelman.shadow"
    id "io.micronaut.application"
    id "io.micronaut.aot"
    id "org.owasp.dependencycheck"
    id "com.andrzejpiontek.version-bump"
    id "org.ajoberstar.grgit" version "5.0.0-rc.3"
}

version = "0.48.72"
group = "com.poliglotek"

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    // micronaut
    annotationProcessor "io.micronaut.validation:micronaut-validation-processor:_"
    annotationProcessor "io.micronaut.serde:micronaut-serde-processor:_"
    annotationProcessor "io.micronaut:micronaut-http-validation:_"
    implementation "io.micronaut.serde:micronaut-serde-jackson:_"
    implementation "io.micronaut.validation:micronaut-validation:_"
    implementation "io.micronaut:micronaut-http-client:_"
    testImplementation "io.micronaut:micronaut-http-client:_"

    // lombok
    annotationProcessor "org.projectlombok:lombok:_"
    testAnnotationProcessor "org.projectlombok:lombok:_"
    implementation "org.projectlombok:lombok:_"
    testCompileOnly "org.projectlombok:lombok:_"

    // jsoup
    implementation "org.jsoup:jsoup:_"

    // selenium
    implementation "org.seleniumhq.selenium:selenium-java:_"

    // google cloud
    implementation "com.google.cloud:google-cloud-translate:_"

    // snakeyaml
    implementation "org.yaml:snakeyaml:_"

    // mailgun
    implementation "com.mailgun:mailgun-java:_"

    // logback
    implementation "ch.qos.logback:logback-classic:_"

    // byte buddy - used by spock to mock classes and generate mock implementations
    testImplementation "net.bytebuddy:byte-buddy:_"

    // objenesis - used by spock to mock classes without default constructors
    testImplementation "org.objenesis:objenesis:_"
}

application {
    mainClass = "com.poliglotek.Application"
}

java {
    sourceCompatibility = JavaVersion.toVersion("21")
    targetCompatibility = JavaVersion.toVersion("21")
}

micronaut {
    runtime "netty"
    testRuntime "spock2"
    processing {
        incremental true
        annotations "com.poliglotek.*"
    }
    aot {
        // https://micronaut-projects.github.io/micronaut-aot/latest/guide/
        optimizeServiceLoading = false
        convertYamlToJava = false
        precomputeOperations = true
        cacheEnvironment = true
        optimizeClassLoading = true
        deduceEnvironment = true
        optimizeNetty = true
        replaceLogbackXml = true
    }
}

dependencyCheck {
    nvd {
        apiKey = System.getenv("nvdApiKey")
    }
}

tasks.register("installGitHook", Copy) {
    from new File(rootProject.rootDir, "scripts/pre-commit")
    into { new File(rootProject.rootDir, ".git/hooks") }
    fileMode 0755
}

tasks.named("compileJava") {
    dependsOn installGitHook
}

versionBump{ }

tasks.register("buildFrontend", Exec) {
    def frontEndEnv = project.hasProperty("frontEndEnv") ? project.getProperty("frontEndEnv") : "prod"
    workingDir "src/frontend"
    if (frontEndEnv == "dev") {
        commandLine "npm", "run", "build-dev"
    } else {
        commandLine "npm", "run", "build-prod"
    }
}

tasks.register("copyFrontend", Copy) {
    dependsOn buildFrontend
    from "src/frontend/dist/frontend"
    into "src/main/resources/public"
}

tasks.named("copyFrontend") {
    outputs.dir("src/main/resources/public")
}

tasks.named("processResources") {
    dependsOn copyFrontend
}

tasks.named("classes") {
    dependsOn copyFrontend
}

tasks.named("inspectRuntimeClasspath") {
    dependsOn copyFrontend
}

tasks.withType(Test).configureEach {// Excludes tests when running build
    enabled = false
}

build.dependsOn copyFrontend
