import { Country } from '../models/country';
import { CountryValue } from '../types/country-value';

export const COUNTRIES: Record<CountryValue, Country> = {
  countryAF: { countryValue: 'countryAF', countryViewValue: 'Afganistan' },
  countryAL: { countryValue: 'countryAL', countryViewValue: 'Albania' },
  countryDZ: { countryValue: 'countryDZ', countryViewValue: 'Algieria' },
  countryAS: { countryValue: 'countryAS', countryViewValue: 'Samoa Amerykańskie' },
  countryAD: { countryValue: 'countryAD', countryViewValue: 'Andora' },
  countryAO: { countryValue: 'countryAO', countryViewValue: 'Angola' },
  countryAI: { countryValue: 'countryAI', countryViewValue: 'Anguilla' },
  countryAQ: { countryValue: 'countryAQ', countryViewValue: 'Antarktyda' },
  countryAG: { countryValue: 'countryAG', countryViewValue: 'Antigua i Barbuda' },
  countryAR: { countryValue: 'countryAR', countryViewValue: 'Argentyna' },
  countryAM: { countryValue: 'countryAM', countryViewValue: 'Armenia' },
  countryAW: { countryValue: 'countryAW', countryViewValue: 'Aruba' },
  countryAU: { countryValue: 'countryAU', countryViewValue: 'Australia' },
  countryAT: { countryValue: 'countryAT', countryViewValue: 'Austria' },
  countryAZ: { countryValue: 'countryAZ', countryViewValue: 'Azerbejdżan' },
  countryBS: { countryValue: 'countryBS', countryViewValue: 'Bahamy' },
  countryBH: { countryValue: 'countryBH', countryViewValue: 'Bahrajn' },
  countryBD: { countryValue: 'countryBD', countryViewValue: 'Bangladesz' },
  countryBB: { countryValue: 'countryBB', countryViewValue: 'Barbados' },
  countryBY: { countryValue: 'countryBY', countryViewValue: 'Białoruś' },
  countryBE: { countryValue: 'countryBE', countryViewValue: 'Belgia' },
  countryBZ: { countryValue: 'countryBZ', countryViewValue: 'Belize' },
  countryBJ: { countryValue: 'countryBJ', countryViewValue: 'Benin' },
  countryBM: { countryValue: 'countryBM', countryViewValue: 'Bermudy' },
  countryBT: { countryValue: 'countryBT', countryViewValue: 'Bhutan' },
  countryBO: { countryValue: 'countryBO', countryViewValue: 'Boliwia' },
  countryBA: { countryValue: 'countryBA', countryViewValue: 'Bośnia i Hercegowina' },
  countryBW: { countryValue: 'countryBW', countryViewValue: 'Botswana' },
  countryBV: { countryValue: 'countryBV', countryViewValue: 'Wyspa Bouvet' },
  countryBR: { countryValue: 'countryBR', countryViewValue: 'Brazylia' },
  countryIO: { countryValue: 'countryIO', countryViewValue: 'Brytyjskie Terytorium Oceanu Indyjskiego' },
  countryBN: { countryValue: 'countryBN', countryViewValue: 'Brunei' },
  countryBG: { countryValue: 'countryBG', countryViewValue: 'Bułgaria' },
  countryBF: { countryValue: 'countryBF', countryViewValue: 'Burkina Faso' },
  countryBI: { countryValue: 'countryBI', countryViewValue: 'Burundi' },
  countryKH: { countryValue: 'countryKH', countryViewValue: 'Kambodża' },
  countryCM: { countryValue: 'countryCM', countryViewValue: 'Kamerun' },
  countryCA: { countryValue: 'countryCA', countryViewValue: 'Kanada' },
  countryCV: { countryValue: 'countryCV', countryViewValue: 'Wyspy Zielonego Przylądka' },
  countryKY: { countryValue: 'countryKY', countryViewValue: 'Wyspy Kajmana' },
  countryCF: { countryValue: 'countryCF', countryViewValue: 'Republika Środkowoafrykańska' },
  countryTD: { countryValue: 'countryTD', countryViewValue: 'Czad' },
  countryCL: { countryValue: 'countryCL', countryViewValue: 'Chile' },
  countryCN: { countryValue: 'countryCN', countryViewValue: 'Chiny' },
  countryCX: { countryValue: 'countryCX', countryViewValue: 'Wyspa Bożego Narodzenia' },
  countryCC: { countryValue: 'countryCC', countryViewValue: 'Wyspy Kokosowe' },
  countryCO: { countryValue: 'countryCO', countryViewValue: 'Kolumbia' },
  countryKM: { countryValue: 'countryKM', countryViewValue: 'Komory' },
  countryCG: { countryValue: 'countryCG', countryViewValue: 'Kongo' },
  countryCD: { countryValue: 'countryCD', countryViewValue: 'Demokratyczna Republika Konga' },
  countryCK: { countryValue: 'countryCK', countryViewValue: 'Wyspy Cooka' },
  countryCR: { countryValue: 'countryCR', countryViewValue: 'Kostaryka' },
  countryCI: { countryValue: 'countryCI', countryViewValue: 'Wybrzeże Kości Słoniowej' },
  countryHR: { countryValue: 'countryHR', countryViewValue: 'Chorwacja' },
  countryCU: { countryValue: 'countryCU', countryViewValue: 'Kuba' },
  countryCY: { countryValue: 'countryCY', countryViewValue: 'Cypr' },
  countryCZ: { countryValue: 'countryCZ', countryViewValue: 'Czechy' },
  countryDK: { countryValue: 'countryDK', countryViewValue: 'Dania' },
  countryDJ: { countryValue: 'countryDJ', countryViewValue: 'Dżibuti' },
  countryDM: { countryValue: 'countryDM', countryViewValue: 'Dominika' },
  countryDO: { countryValue: 'countryDO', countryViewValue: 'Dominikana' },
  countryTP: { countryValue: 'countryTP', countryViewValue: 'Timor Wschodni' },
  countryEC: { countryValue: 'countryEC', countryViewValue: 'Ekwador' },
  countryEG: { countryValue: 'countryEG', countryViewValue: 'Egipt' },
  countrySV: { countryValue: 'countrySV', countryViewValue: 'Salwador' },
  countryGQ: { countryValue: 'countryGQ', countryViewValue: 'Gwinea Równikowa' },
  countryER: { countryValue: 'countryER', countryViewValue: 'Erytrea' },
  countryEE: { countryValue: 'countryEE', countryViewValue: 'Estonia' },
  countryET: { countryValue: 'countryET', countryViewValue: 'Etiopia' },
  countryEU: { countryValue: 'countryEU', countryViewValue: 'Unia Europejska' },
  countryFK: { countryValue: 'countryFK', countryViewValue: 'Falklandy (Malwiny)' },
  countryFO: { countryValue: 'countryFO', countryViewValue: 'Wyspy Owcze' },
  countryFJ: { countryValue: 'countryFJ', countryViewValue: 'Fidżi' },
  countryFI: { countryValue: 'countryFI', countryViewValue: 'Finlandia' },
  countryFR: { countryValue: 'countryFR', countryViewValue: 'Francja' },
  countryFX: { countryValue: 'countryFX', countryViewValue: 'Francja Metropolitalna' },
  countryGF: { countryValue: 'countryGF', countryViewValue: 'Gujana Francuska' },
  countryPF: { countryValue: 'countryPF', countryViewValue: 'Polinezja Francuska' },
  countryTF: { countryValue: 'countryTF', countryViewValue: 'Francuskie Terytoria Południowe' },
  countryGA: { countryValue: 'countryGA', countryViewValue: 'Gabon' },
  countryGM: { countryValue: 'countryGM', countryViewValue: 'Gambia' },
  countryGE: { countryValue: 'countryGE', countryViewValue: 'Gruzja' },
  countryDE: { countryValue: 'countryDE', countryViewValue: 'Niemcy' },
  countryGH: { countryValue: 'countryGH', countryViewValue: 'Ghana' },
  countryGI: { countryValue: 'countryGI', countryViewValue: 'Gibraltar' },
  countryGR: { countryValue: 'countryGR', countryViewValue: 'Grecja' },
  countryGL: { countryValue: 'countryGL', countryViewValue: 'Grenlandia' },
  countryGD: { countryValue: 'countryGD', countryViewValue: 'Grenada' },
  countryGP: { countryValue: 'countryGP', countryViewValue: 'Gwadelupa' },
  countryGU: { countryValue: 'countryGU', countryViewValue: 'Guam' },
  countryGT: { countryValue: 'countryGT', countryViewValue: 'Gwatemala' },
  countryGN: { countryValue: 'countryGN', countryViewValue: 'Gwinea' },
  countryGW: { countryValue: 'countryGW', countryViewValue: 'Gwinea Bissau' },
  countryGY: { countryValue: 'countryGY', countryViewValue: 'Gujana' },
  countryHT: { countryValue: 'countryHT', countryViewValue: 'Haiti' },
  countryHM: { countryValue: 'countryHM', countryViewValue: 'Wyspy Heard i McDonalda' },
  countryVA: { countryValue: 'countryVA', countryViewValue: 'Watykan' },
  countryHN: { countryValue: 'countryHN', countryViewValue: 'Honduras' },
  countryHK: { countryValue: 'countryHK', countryViewValue: 'Hongkong' },
  countryHU: { countryValue: 'countryHU', countryViewValue: 'Węgry' },
  countryIS: { countryValue: 'countryIS', countryViewValue: 'Islandia' },
  countryIN: { countryValue: 'countryIN', countryViewValue: 'Indie' },
  countryID: { countryValue: 'countryID', countryViewValue: 'Indonezja' },
  countryIR: { countryValue: 'countryIR', countryViewValue: 'Iran' },
  countryIQ: { countryValue: 'countryIQ', countryViewValue: 'Irak' },
  countryIE: { countryValue: 'countryIE', countryViewValue: 'Irlandia' },
  countryIL: { countryValue: 'countryIL', countryViewValue: 'Izrael' },
  countryIT: { countryValue: 'countryIT', countryViewValue: 'Włochy' },
  countryJM: { countryValue: 'countryJM', countryViewValue: 'Jamajka' },
  countryJP: { countryValue: 'countryJP', countryViewValue: 'Japonia' },
  countryJO: { countryValue: 'countryJO', countryViewValue: 'Jordania' },
  countryKZ: { countryValue: 'countryKZ', countryViewValue: 'Kazachstan' },
  countryKE: { countryValue: 'countryKE', countryViewValue: 'Kenia' },
  countryKI: { countryValue: 'countryKI', countryViewValue: 'Kiribati' },
  countryKP: { countryValue: 'countryKP', countryViewValue: 'Korea Północna' },
  countryKR: { countryValue: 'countryKR', countryViewValue: 'Korea Południowa' },
  countryKW: { countryValue: 'countryKW', countryViewValue: 'Kuwejt' },
  countryKG: { countryValue: 'countryKG', countryViewValue: 'Kirgistan' },
  countryLA: { countryValue: 'countryLA', countryViewValue: 'Laos' },
  countryLV: { countryValue: 'countryLV', countryViewValue: 'Łotwa' },
  countryLB: { countryValue: 'countryLB', countryViewValue: 'Liban' },
  countryLS: { countryValue: 'countryLS', countryViewValue: 'Lesotho' },
  countryLR: { countryValue: 'countryLR', countryViewValue: 'Liberia' },
  countryLY: { countryValue: 'countryLY', countryViewValue: 'Libia' },
  countryLI: { countryValue: 'countryLI', countryViewValue: 'Liechtenstein' },
  countryLT: { countryValue: 'countryLT', countryViewValue: 'Litwa' },
  countryLU: { countryValue: 'countryLU', countryViewValue: 'Luksemburg' },
  countryMO: { countryValue: 'countryMO', countryViewValue: 'Makau' },
  countryMK: { countryValue: 'countryMK', countryViewValue: 'Macedonia' },
  countryMG: { countryValue: 'countryMG', countryViewValue: 'Madagaskar' },
  countryMW: { countryValue: 'countryMW', countryViewValue: 'Malawi' },
  countryMY: { countryValue: 'countryMY', countryViewValue: 'Malezja' },
  countryMV: { countryValue: 'countryMV', countryViewValue: 'Malediwy' },
  countryML: { countryValue: 'countryML', countryViewValue: 'Mali' },
  countryMT: { countryValue: 'countryMT', countryViewValue: 'Malta' },
  countryMH: { countryValue: 'countryMH', countryViewValue: 'Wyspy Marshalla' },
  countryMQ: { countryValue: 'countryMQ', countryViewValue: 'Martynika' },
  countryMR: { countryValue: 'countryMR', countryViewValue: 'Mauretania' },
  countryMU: { countryValue: 'countryMU', countryViewValue: 'Mauritius' },
  countryYT: { countryValue: 'countryYT', countryViewValue: 'Majotta' },
  countryMX: { countryValue: 'countryMX', countryViewValue: 'Meksyk' },
  countryFM: { countryValue: 'countryFM', countryViewValue: 'Mikronezja' },
  countryMD: { countryValue: 'countryMD', countryViewValue: 'Mołdawia' },
  countryMC: { countryValue: 'countryMC', countryViewValue: 'Monako' },
  countryMN: { countryValue: 'countryMN', countryViewValue: 'Mongolia' },
  countryME: { countryValue: 'countryME', countryViewValue: 'Czarnogóra' },
  countryMS: { countryValue: 'countryMS', countryViewValue: 'Montserrat' },
  countryMA: { countryValue: 'countryMA', countryViewValue: 'Maroko' },
  countryMZ: { countryValue: 'countryMZ', countryViewValue: 'Mozambik' },
  countryMM: { countryValue: 'countryMM', countryViewValue: 'Myanmar' },
  countryNA: { countryValue: 'countryNA', countryViewValue: 'Namibia' },
  countryNR: { countryValue: 'countryNR', countryViewValue: 'Nauru' },
  countryNP: { countryValue: 'countryNP', countryViewValue: 'Nepal' },
  countryNL: { countryValue: 'countryNL', countryViewValue: 'Holandia' },
  countryNC: { countryValue: 'countryNC', countryViewValue: 'Nowa Kaledonia' },
  countryNZ: { countryValue: 'countryNZ', countryViewValue: 'Nowa Zelandia' },
  countryNI: { countryValue: 'countryNI', countryViewValue: 'Nikaragua' },
  countryNE: { countryValue: 'countryNE', countryViewValue: 'Niger' },
  countryNG: { countryValue: 'countryNG', countryViewValue: 'Nigeria' },
  countryNU: { countryValue: 'countryNU', countryViewValue: 'Niue' },
  countryNF: { countryValue: 'countryNF', countryViewValue: 'Wyspa Norfolk' },
  countryMP: { countryValue: 'countryMP', countryViewValue: 'Mariany Północne' },
  countryNO: { countryValue: 'countryNO', countryViewValue: 'Norwegia' },
  countryOM: { countryValue: 'countryOM', countryViewValue: 'Oman' },
  countryPK: { countryValue: 'countryPK', countryViewValue: 'Pakistan' },
  countryPW: { countryValue: 'countryPW', countryViewValue: 'Palau' },
  countryPS: { countryValue: 'countryPS', countryViewValue: 'Palestyna' },
  countryPA: { countryValue: 'countryPA', countryViewValue: 'Panama' },
  countryPG: { countryValue: 'countryPG', countryViewValue: 'Papua-Nowa Gwinea' },
  countryPY: { countryValue: 'countryPY', countryViewValue: 'Paragwaj' },
  countryPE: { countryValue: 'countryPE', countryViewValue: 'Peru' },
  countryPH: { countryValue: 'countryPH', countryViewValue: 'Filipiny' },
  countryPN: { countryValue: 'countryPN', countryViewValue: 'Pitcairn' },
  countryPL: { countryValue: 'countryPL', countryViewValue: 'Polska' },
  countryPT: { countryValue: 'countryPT', countryViewValue: 'Portugalia' },
  countryPR: { countryValue: 'countryPR', countryViewValue: 'Portoryko' },
  countryQA: { countryValue: 'countryQA', countryViewValue: 'Katar' },
  countryRE: { countryValue: 'countryRE', countryViewValue: 'Reunion' },
  countryRO: { countryValue: 'countryRO', countryViewValue: 'Rumunia' },
  countryRU: { countryValue: 'countryRU', countryViewValue: 'Rosja' },
  countryRW: { countryValue: 'countryRW', countryViewValue: 'Rwanda' },
  countrySH: { countryValue: 'countrySH', countryViewValue: 'Święta Helena' },
  countryKN: { countryValue: 'countryKN', countryViewValue: 'Saint Kitts i Nevis' },
  countryLC: { countryValue: 'countryLC', countryViewValue: 'Saint Lucia' },
  countryPM: { countryValue: 'countryPM', countryViewValue: 'Saint Pierre i Miquelon' },
  countryVC: { countryValue: 'countryVC', countryViewValue: 'Saint Vincent i Grenadyny' },
  countryWS: { countryValue: 'countryWS', countryViewValue: 'Samoa' },
  countrySM: { countryValue: 'countrySM', countryViewValue: 'San Marino' },
  countryST: { countryValue: 'countryST', countryViewValue: 'Sao Tome i Principe' },
  countrySA: { countryValue: 'countrySA', countryViewValue: 'Arabia Saudyjska' },
  countrySN: { countryValue: 'countrySN', countryViewValue: 'Senegal' },
  countryCS: { countryValue: 'countryCS', countryViewValue: 'Serbia i Czarnogóra' },
  countrySC: { countryValue: 'countrySC', countryViewValue: 'Seszele' },
  countrySL: { countryValue: 'countrySL', countryViewValue: 'Sierra Leone' },
  countrySG: { countryValue: 'countrySG', countryViewValue: 'Singapur' },
  countrySK: { countryValue: 'countrySK', countryViewValue: 'Słowacja' },
  countrySI: { countryValue: 'countrySI', countryViewValue: 'Słowenia' },
  countrySB: { countryValue: 'countrySB', countryViewValue: 'Wyspy Salomona' },
  countrySO: { countryValue: 'countrySO', countryViewValue: 'Somalia' },
  countryZA: { countryValue: 'countryZA', countryViewValue: 'Republika Południowej Afryki' },
  countryGS: { countryValue: 'countryGS', countryViewValue: 'Georgia Południowa i Sandwich Południowy' },
  countryES: { countryValue: 'countryES', countryViewValue: 'Hiszpania' },
  countryLK: { countryValue: 'countryLK', countryViewValue: 'Sri Lanka' },
  countrySD: { countryValue: 'countrySD', countryViewValue: 'Sudan' },
  countrySR: { countryValue: 'countrySR', countryViewValue: 'Surinam' },
  countrySJ: { countryValue: 'countrySJ', countryViewValue: 'Svalbard i Jan Mayen' },
  countrySZ: { countryValue: 'countrySZ', countryViewValue: 'Eswatini' },
  countrySE: { countryValue: 'countrySE', countryViewValue: 'Szwecja' },
  countryCH: { countryValue: 'countryCH', countryViewValue: 'Szwajcaria' },
  countrySY: { countryValue: 'countrySY', countryViewValue: 'Syria' },
  countryTW: { countryValue: 'countryTW', countryViewValue: 'Tajwan' },
  countryTJ: { countryValue: 'countryTJ', countryViewValue: 'Tadżykistan' },
  countryTZ: { countryValue: 'countryTZ', countryViewValue: 'Tanzania' },
  countryTH: { countryValue: 'countryTH', countryViewValue: 'Tajlandia' },
  countryTG: { countryValue: 'countryTG', countryViewValue: 'Togo' },
  countryTK: { countryValue: 'countryTK', countryViewValue: 'Tokelau' },
  countryTO: { countryValue: 'countryTO', countryViewValue: 'Tonga' },
  countryTT: { countryValue: 'countryTT', countryViewValue: 'Trynidad i Tobago' },
  countryTN: { countryValue: 'countryTN', countryViewValue: 'Tunezja' },
  countryTR: { countryValue: 'countryTR', countryViewValue: 'Turcja' },
  countryTM: { countryValue: 'countryTM', countryViewValue: 'Turkmenistan' },
  countryTC: { countryValue: 'countryTC', countryViewValue: 'Wyspy Turks i Caicos' },
  countryTV: { countryValue: 'countryTV', countryViewValue: 'Tuvalu' },
  countryUG: { countryValue: 'countryUG', countryViewValue: 'Uganda' },
  countryUA: { countryValue: 'countryUA', countryViewValue: 'Ukraina' },
  countryAE: { countryValue: 'countryAE', countryViewValue: 'Zjednoczone Emiraty Arabskie' },
  countryUK: { countryValue: 'countryUK', countryViewValue: 'Wielka Brytania' },
  countryUS: { countryValue: 'countryUS', countryViewValue: 'Stany Zjednoczone' },
  countryUM: { countryValue: 'countryUM', countryViewValue: 'Mniejsze Wyspy Owtoczne Stanów Zjednoczonych' },
  countryUY: { countryValue: 'countryUY', countryViewValue: 'Urugwaj' },
  countryUZ: { countryValue: 'countryUZ', countryViewValue: 'Uzbekistan' },
  countryVU: { countryValue: 'countryVU', countryViewValue: 'Vanuatu' },
  countryVE: { countryValue: 'countryVE', countryViewValue: 'Wenezuela' },
  countryVN: { countryValue: 'countryVN', countryViewValue: 'Wietnam' },
  countryWF: { countryValue: 'countryWF', countryViewValue: 'Wallis i Futuna' },
  countryEH: { countryValue: 'countryEH', countryViewValue: 'Sahara Zachodnia' },
  countryYE: { countryValue: 'countryYE', countryViewValue: 'Jemen' },
  countryZM: { countryValue: 'countryZM', countryViewValue: 'Zambia' },
  countryZW: { countryValue: 'countryZW', countryViewValue: 'Zimbabwe' },
};
