import { Country } from '../models/country';

export const COUNTRIES: Country[] = [
  { countryValue: 'countryAF', countryViewValue: 'Afganistan' },
  { countryValue: 'countryAL', countryViewValue: 'Albania' },
  { countryValue: 'countryDZ', countryViewValue: 'Algieria' },
  { countryValue: 'countryAS', countryViewValue: 'Samoa Amerykańskie' },
  { countryValue: 'countryAD', countryViewValue: 'Andora' },
  { countryValue: 'countryAO', countryViewValue: 'Angola' },
  { countryValue: 'countryAI', countryViewValue: 'Anguilla' },
  { countryValue: 'countryAQ', countryViewValue: 'Antarktyda' },
  { countryValue: 'countryAG', countryViewValue: 'Antigua i Barbuda' },
  { countryValue: 'countryAR', countryViewValue: 'Argentyna' },
  { countryValue: 'countryAM', countryViewValue: 'Armenia' },
  { countryValue: 'countryAW', countryViewValue: 'Aruba' },
  { countryValue: 'countryAU', countryViewValue: 'Australia' },
  { countryValue: 'countryAT', countryViewValue: 'Austria' },
  { countryValue: 'countryAZ', countryViewValue: 'Azerbejdżan' },
  { countryValue: 'countryBS', countryViewValue: 'Bahamy' },
  { countryValue: 'countryBH', countryViewValue: 'Bahrajn' },
  { countryValue: 'countryBD', countryViewValue: 'Bangladesz' },
  { countryValue: 'countryBB', countryViewValue: 'Barbados' },
  { countryValue: 'countryBY', countryViewValue: 'Białoruś' },
  { countryValue: 'countryBE', countryViewValue: 'Belgia' },
  { countryValue: 'countryBZ', countryViewValue: 'Belize' },
  { countryValue: 'countryBJ', countryViewValue: 'Benin' },
  { countryValue: 'countryBM', countryViewValue: 'Bermudy' },
  { countryValue: 'countryBT', countryViewValue: 'Bhutan' },
  { countryValue: 'countryBO', countryViewValue: 'Boliwia' },
  { countryValue: 'countryBA', countryViewValue: 'Bośnia i Hercegowina' },
  { countryValue: 'countryBW', countryViewValue: 'Botswana' },
  { countryValue: 'countryBV', countryViewValue: 'Wyspa Bouvet' },
  { countryValue: 'countryBR', countryViewValue: 'Brazylia' },
  { countryValue: 'countryIO', countryViewValue: 'Brytyjskie Terytorium Oceanu Indyjskiego' },
  { countryValue: 'countryBN', countryViewValue: 'Brunei' },
  { countryValue: 'countryBG', countryViewValue: 'Bułgaria' },
  { countryValue: 'countryBF', countryViewValue: 'Burkina Faso' },
  { countryValue: 'countryBI', countryViewValue: 'Burundi' },
  { countryValue: 'countryKH', countryViewValue: 'Kambodża' },
  { countryValue: 'countryCM', countryViewValue: 'Kamerun' },
  { countryValue: 'countryCA', countryViewValue: 'Kanada' },
  { countryValue: 'countryCV', countryViewValue: 'Wyspy Zielonego Przylądka' },
  { countryValue: 'countryKY', countryViewValue: 'Wyspy Kajmana' },
  { countryValue: 'countryCF', countryViewValue: 'Republika Środkowoafrykańska' },
  { countryValue: 'countryTD', countryViewValue: 'Czad' },
  { countryValue: 'countryCL', countryViewValue: 'Chile' },
  { countryValue: 'countryCN', countryViewValue: 'Chiny' },
  { countryValue: 'countryCX', countryViewValue: 'Wyspa Bożego Narodzenia' },
  { countryValue: 'countryCC', countryViewValue: 'Wyspy Kokosowe' },
  { countryValue: 'countryCO', countryViewValue: 'Kolumbia' },
  { countryValue: 'countryKM', countryViewValue: 'Komory' },
  { countryValue: 'countryCG', countryViewValue: 'Kongo' },
  { countryValue: 'countryCD', countryViewValue: 'Demokratyczna Republika Konga' },
  { countryValue: 'countryCK', countryViewValue: 'Wyspy Cooka' },
  { countryValue: 'countryCR', countryViewValue: 'Kostaryka' },
  { countryValue: 'countryCI', countryViewValue: 'Wybrzeże Kości Słoniowej' },
  { countryValue: 'countryHR', countryViewValue: 'Chorwacja' },
  { countryValue: 'countryCU', countryViewValue: 'Kuba' },
  { countryValue: 'countryCY', countryViewValue: 'Cypr' },
  { countryValue: 'countryCZ', countryViewValue: 'Czechy' },
  { countryValue: 'countryDK', countryViewValue: 'Dania' },
  { countryValue: 'countryDJ', countryViewValue: 'Dżibuti' },
  { countryValue: 'countryDM', countryViewValue: 'Dominika' },
  { countryValue: 'countryDO', countryViewValue: 'Republika Dominikańska' },
  { countryValue: 'countryTP', countryViewValue: 'Timor Wschodni' },
  { countryValue: 'countryEC', countryViewValue: 'Ekwador' },
  { countryValue: 'countryEG', countryViewValue: 'Egipt' },
  { countryValue: 'countrySV', countryViewValue: 'Salwador' },
  { countryValue: 'countryGQ', countryViewValue: 'Gwinea Równikowa' },
  { countryValue: 'countryER', countryViewValue: 'Erytrea' },
  { countryValue: 'countryEE', countryViewValue: 'Estonia' },
  { countryValue: 'countryET', countryViewValue: 'Etiopia' },
  { countryValue: 'countryEU', countryViewValue: 'Unia Europejska' },
  { countryValue: 'countryFK', countryViewValue: 'Falklandy (Malwiny)' },
  { countryValue: 'countryFO', countryViewValue: 'Wyspy Owcze' },
  { countryValue: 'countryFJ', countryViewValue: 'Fidżi' },
  { countryValue: 'countryFI', countryViewValue: 'Finlandia' },
  { countryValue: 'countryFR', countryViewValue: 'Francja' },
  { countryValue: 'countryFX', countryViewValue: 'Francja Metropolitalna' },
  { countryValue: 'countryGF', countryViewValue: 'Gujana Francuska' },
  { countryValue: 'countryPF', countryViewValue: 'Polinezja Francuska' },
  { countryValue: 'countryTF', countryViewValue: 'Francuskie Terytoria Południowe' },
  { countryValue: 'countryGA', countryViewValue: 'Gabon' },
  { countryValue: 'countryGM', countryViewValue: 'Gambia' },
  { countryValue: 'countryGE', countryViewValue: 'Gruzja' },
  { countryValue: 'countryDE', countryViewValue: 'Niemcy' },
  { countryValue: 'countryGH', countryViewValue: 'Ghana' },
  { countryValue: 'countryGI', countryViewValue: 'Gibraltar' },
  { countryValue: 'countryGR', countryViewValue: 'Grecja' },
  { countryValue: 'countryGL', countryViewValue: 'Grenlandia' },
  { countryValue: 'countryGD', countryViewValue: 'Grenada' },
  { countryValue: 'countryGP', countryViewValue: 'Gwadelupa' },
  { countryValue: 'countryGU', countryViewValue: 'Guam' },
  { countryValue: 'countryGT', countryViewValue: 'Gwatemala' },
  { countryValue: 'countryGN', countryViewValue: 'Gwinea' },
  { countryValue: 'countryGW', countryViewValue: 'Gwinea Bissau' },
  { countryValue: 'countryGY', countryViewValue: 'Gujana' },
  { countryValue: 'countryHT', countryViewValue: 'Haiti' },
  { countryValue: 'countryHM', countryViewValue: 'Wyspy Heard i McDonalda' },
  { countryValue: 'countryVA', countryViewValue: 'Stolica Apostolska (Watykan)' },
  { countryValue: 'countryHN', countryViewValue: 'Honduras' },
  { countryValue: 'countryHK', countryViewValue: 'Hongkong' },
  { countryValue: 'countryHU', countryViewValue: 'Węgry' },
  { countryValue: 'countryIS', countryViewValue: 'Islandia' },
  { countryValue: 'countryIN', countryViewValue: 'Indie' },
  { countryValue: 'countryID', countryViewValue: 'Indonezja' },
  { countryValue: 'countryIR', countryViewValue: 'Iran' },
  { countryValue: 'countryIQ', countryViewValue: 'Irak' },
  { countryValue: 'countryIE', countryViewValue: 'Irlandia' },
  { countryValue: 'countryIL', countryViewValue: 'Izrael' },
  { countryValue: 'countryIT', countryViewValue: 'Włochy' },
  { countryValue: 'countryJM', countryViewValue: 'Jamajka' },
  { countryValue: 'countryJP', countryViewValue: 'Japonia' },
  { countryValue: 'countryJO', countryViewValue: 'Jordania' },
  { countryValue: 'countryKZ', countryViewValue: 'Kazachstan' },
  { countryValue: 'countryKE', countryViewValue: 'Kenia' },
  { countryValue: 'countryKI', countryViewValue: 'Kiribati' },
  { countryValue: 'countryKP', countryViewValue: 'Korea Północna' },
  { countryValue: 'countryKR', countryViewValue: 'Korea Południowa' },
  { countryValue: 'countryKW', countryViewValue: 'Kuwejt' },
  { countryValue: 'countryKG', countryViewValue: 'Kirgistan' },
  { countryValue: 'countryLA', countryViewValue: 'Laońska Republika Ludowa' },
  { countryValue: 'countryLV', countryViewValue: 'Łotwa' },
  { countryValue: 'countryLB', countryViewValue: 'Liban' },
  { countryValue: 'countryLS', countryViewValue: 'Lesotho' },
  { countryValue: 'countryLR', countryViewValue: 'Liberia' },
  { countryValue: 'countryLY', countryViewValue: 'Libia' },
  { countryValue: 'countryLI', countryViewValue: 'Liechtenstein' },
  { countryValue: 'countryLT', countryViewValue: 'Litwa' },
  { countryValue: 'countryLU', countryViewValue: 'Luksemburg' },
  { countryValue: 'countryMO', countryViewValue: 'Macao' },
  { countryValue: 'countryMK', countryViewValue: 'Macedonia' },
  { countryValue: 'countryMG', countryViewValue: 'Madagaskar' },
  { countryValue: 'countryMW', countryViewValue: 'Malawi' },
  { countryValue: 'countryMY', countryViewValue: 'Malezja' },
  { countryValue: 'countryMV', countryViewValue: 'Malediwy' },
  { countryValue: 'countryML', countryViewValue: 'Mali' },
  { countryValue: 'countryMT', countryViewValue: 'Malta' },
  { countryValue: 'countryMH', countryViewValue: 'Wyspy Marshalla' },
  { countryValue: 'countryMQ', countryViewValue: 'Martynika' },
  { countryValue: 'countryMR', countryViewValue: 'Mauretania' },
  { countryValue: 'countryMU', countryViewValue: 'Mauritius' },
  { countryValue: 'countryYT', countryViewValue: 'Majotta' },
  { countryValue: 'countryMX', countryViewValue: 'Meksyk' },
  { countryValue: 'countryFM', countryViewValue: 'Mikronezja' },
  { countryValue: 'countryMD', countryViewValue: 'Mołdawia' },
  { countryValue: 'countryMC', countryViewValue: 'Monako' },
  { countryValue: 'countryMN', countryViewValue: 'Mongolia' },
  { countryValue: 'countryMS', countryViewValue: 'Montserrat' },
  { countryValue: 'countryMA', countryViewValue: 'Maroko' },
  { countryValue: 'countryMZ', countryViewValue: 'Mozambik' },
  { countryValue: 'countryMM', countryViewValue: 'Mjanma' },
  { countryValue: 'countryNA', countryViewValue: 'Namibia' },
  { countryValue: 'countryNR', countryViewValue: 'Nauru' },
  { countryValue: 'countryNP', countryViewValue: 'Nepal' },
  { countryValue: 'countryNL', countryViewValue: 'Holandia' },
  { countryValue: 'countryAN', countryViewValue: 'Antyle Holenderskie' },
  { countryValue: 'countryNC', countryViewValue: 'Nowa Kaledonia' },
  { countryValue: 'countryNZ', countryViewValue: 'Nowa Zelandia' },
  { countryValue: 'countryNI', countryViewValue: 'Nikaragua' },
  { countryValue: 'countryNE', countryViewValue: 'Niger' },
  { countryValue: 'countryNG', countryViewValue: 'Nigeria' },
  { countryValue: 'countryNU', countryViewValue: 'Niue' },
  { countryValue: 'countryNF', countryViewValue: 'Wyspa Norfolk' },
  { countryValue: 'countryMP', countryViewValue: 'Północne Wyspy Mariana' },
  { countryValue: 'countryNO', countryViewValue: 'Norwegia' },
  { countryValue: 'countryOM', countryViewValue: 'Oman' },
  { countryValue: 'countryPK', countryViewValue: 'Pakistan' },
  { countryValue: 'countryPW', countryViewValue: 'Palau' },
  { countryValue: 'countryPS', countryViewValue: 'Terytorium Palestyńskie' },
  { countryValue: 'countryPA', countryViewValue: 'Panama' },
  { countryValue: 'countryPG', countryViewValue: 'Papua-Nowa Gwinea' },
  { countryValue: 'countryPY', countryViewValue: 'Paragwaj' },
  { countryValue: 'countryPE', countryViewValue: 'Peru' },
  { countryValue: 'countryPH', countryViewValue: 'Filipiny' },
  { countryValue: 'countryPN', countryViewValue: 'Pitcairn' },
  { countryValue: 'countryPL', countryViewValue: 'Polska' },
  { countryValue: 'countryPT', countryViewValue: 'Portugalia' },
  { countryValue: 'countryPR', countryViewValue: 'Portoryko' },
  { countryValue: 'countryQA', countryViewValue: 'Katar' },
  { countryValue: 'countryRE', countryViewValue: 'Reunion' },
  { countryValue: 'countryRO', countryViewValue: 'Rumunia' },
  { countryValue: 'countryRU', countryViewValue: 'Federacja Rosyjska' },
  { countryValue: 'countryRW', countryViewValue: 'Rwanda' },
  { countryValue: 'countrySH', countryViewValue: 'Wyspa Świętej Heleny' },
  { countryValue: 'countryKN', countryViewValue: 'Saint Kitts i Nevis' },
  { countryValue: 'countryLC', countryViewValue: 'Saint Lucia' },
  { countryValue: 'countryPM', countryViewValue: 'Saint Pierre i Miquelon' },
  { countryValue: 'countryVC', countryViewValue: 'Saint Vincent i Grenadyny' },
  { countryValue: 'countryWS', countryViewValue: 'Samoa' },
  { countryValue: 'countrySM', countryViewValue: 'San Marino' },
  { countryValue: 'countryST', countryViewValue: 'Sao Tome i Principe' },
  { countryValue: 'countrySA', countryViewValue: 'Arabia Saudyjska' },
  { countryValue: 'countrySN', countryViewValue: 'Senegal' },
  { countryValue: 'countryCS', countryViewValue: 'Serbia i Czarnogóra' },
  { countryValue: 'countrySC', countryViewValue: 'Seszele' },
  { countryValue: 'countrySL', countryViewValue: 'Sierra Leone' },
  { countryValue: 'countrySG', countryViewValue: 'Singapur' },
  { countryValue: 'countrySK', countryViewValue: 'Słowacja' },
  { countryValue: 'countrySI', countryViewValue: 'Słowenia' },
  { countryValue: 'countrySB', countryViewValue: 'Wyspy Salomona' },
  { countryValue: 'countrySO', countryViewValue: 'Somalia' },
  { countryValue: 'countryZA', countryViewValue: 'Republika Południowej Afryki' },
  { countryValue: 'countryGS', countryViewValue: 'Georgia Południowa i Sandwich Południowy' },
  { countryValue: 'countryES', countryViewValue: 'Hiszpania' },
  { countryValue: 'countryLK', countryViewValue: 'Sri Lanka' },
  { countryValue: 'countrySD', countryViewValue: 'Sudan' },
  { countryValue: 'countrySR', countryViewValue: 'Surinam' },
  { countryValue: 'countrySJ', countryViewValue: 'Svalbard i Jan Mayen' },
  { countryValue: 'countrySZ', countryViewValue: 'Eswatini' },
  { countryValue: 'countrySE', countryViewValue: 'Szwecja' },
  { countryValue: 'countryCH', countryViewValue: 'Szwajcaria' },
  { countryValue: 'countrySY', countryViewValue: 'Syria' },
  { countryValue: 'countryTW', countryViewValue: 'Tajwan' },
  { countryValue: 'countryTJ', countryViewValue: 'Tadżykistan' },
  { countryValue: 'countryTZ', countryViewValue: 'Tanzania' },
  { countryValue: 'countryTH', countryViewValue: 'Tajlandia' },
  { countryValue: 'countryTG', countryViewValue: 'Togo' },
  { countryValue: 'countryTK', countryViewValue: 'Tokelau' },
  { countryValue: 'countryTO', countryViewValue: 'Tonga' },
  { countryValue: 'countryTT', countryViewValue: 'Trynidad i Tobago' },
  { countryValue: 'countryTN', countryViewValue: 'Tunezja' },
  { countryValue: 'countryTR', countryViewValue: 'Turcja' },
  { countryValue: 'countryTM', countryViewValue: 'Turkmenistan' },
  { countryValue: 'countryTC', countryViewValue: 'Wyspy Turks i Caicos' },
  { countryValue: 'countryTV', countryViewValue: 'Tuvalu' },
  { countryValue: 'countryUG', countryViewValue: 'Uganda' },
  { countryValue: 'countryUA', countryViewValue: 'Ukraina' },
  { countryValue: 'countryAE', countryViewValue: 'Zjednoczone Emiraty Arabskie' },
  { countryValue: 'countryUK', countryViewValue: 'Wielka Brytania' },
  { countryValue: 'countryUS', countryViewValue: 'Stany Zjednoczone' },
  { countryValue: 'countryUM', countryViewValue: 'Mniejsze Wyspy Owtoczne Stanów Zjednoczonych' },
  { countryValue: 'countryUY', countryViewValue: 'Urugwaj' },
  { countryValue: 'countryUZ', countryViewValue: 'Uzbekistan' },
  { countryValue: 'countryVU', countryViewValue: 'Vanuatu' },
  { countryValue: 'countryVE', countryViewValue: 'Wenezuela' },
  { countryValue: 'countryVN', countryViewValue: 'Wietnam' },
  { countryValue: 'countryWF', countryViewValue: 'Wallis i Futuna' },
  { countryValue: 'countryEH', countryViewValue: 'Sahara Zachodnia' },
  { countryValue: 'countryYE', countryViewValue: 'Jemen' },
  { countryValue: 'countryZM', countryViewValue: 'Zambia' },
  { countryValue: 'countryZW', countryViewValue: 'Zimbabwe' }
];
