import { Country } from '../models/country';
import { LanguageValue } from '../types/language-value';
import { COUNTRIES } from './countries';

export const LANG_COUNTRY_MATCH: Record<LanguageValue, Country | Country[]> = {
  'af': COUNTRIES.countryZA,
  'sq': COUNTRIES.countryAL,
  'am': COUNTRIES.countryET,
  'hy': COUNTRIES.countryAM,
  'az': COUNTRIES.countryAZ,
  'bm': COUNTRIES.countryML,
  'eu': COUNTRIES.countryES,
  'be': COUNTRIES.countryBY,
  'bs': COUNTRIES.countryBA,
  'bg': COUNTRIES.countryBG,
  'ca': COUNTRIES.countryES,
  'ceb': COUNTRIES.countryPH,
  'co': COUNTRIES.countryFR,
  'hr': COUNTRIES.countryHR,
  'cs': COUNTRIES.countryCZ,
  'da': COUNTRIES.countryDK,
  'dv': COUNTRIES.countryMV,
  'doi': COUNTRIES.countryIN,
  'et': COUNTRIES.countryEE,
  'fil': COUNTRIES.countryPH,
  'fi': COUNTRIES.countryFI,
  'fy': COUNTRIES.countryNL,
  'gl': COUNTRIES.countryES,
  'ka': COUNTRIES.countryGE,
  'de': COUNTRIES.countryDE,
  'el': COUNTRIES.countryGR,
  'gn': COUNTRIES.countryPY,
  'gu': COUNTRIES.countryIN,
  'ht': COUNTRIES.countryHT,
  'ha': COUNTRIES.countryNE,
  'haw': COUNTRIES.countryUS,
  'he': COUNTRIES.countryIL,
  'hi': COUNTRIES.countryIN,
  'hu': COUNTRIES.countryHU,
  'is': COUNTRIES.countryIS,
  'ig': COUNTRIES.countryNG,
  'ilo': COUNTRIES.countryPH,
  'id': COUNTRIES.countryID,
  'ga': COUNTRIES.countryIE,
  'it': COUNTRIES.countryIT,
  'ja': COUNTRIES.countryJP,
  'jv': COUNTRIES.countryID,
  'kn': COUNTRIES.countryIN,
  'kk': COUNTRIES.countryKZ,
  'km': COUNTRIES.countryKH,
  'gom': COUNTRIES.countryIN,
  'kri': COUNTRIES.countrySL,
  'ckb': COUNTRIES.countryIQ,
  'ky': COUNTRIES.countryKG,
  'lo': COUNTRIES.countryLA,
  'lv': COUNTRIES.countryLV,
  'ln': COUNTRIES.countryCG,
  'lt': COUNTRIES.countryLT,
  'lg': COUNTRIES.countryUG,
  'lb': COUNTRIES.countryLU,
  'mk': COUNTRIES.countryMK,
  'mai': COUNTRIES.countryIN,
  'mg': COUNTRIES.countryMG,
  'ml': COUNTRIES.countryIN,
  'mt': COUNTRIES.countryMT,
  'mi': COUNTRIES.countryNZ,
  'mr': COUNTRIES.countryIN,
  'lus': COUNTRIES.countryIN,
  'mn': COUNTRIES.countryMN,
  'my': COUNTRIES.countryMM,
  'ne': COUNTRIES.countryNP,
  'no': COUNTRIES.countryNO,
  'or': COUNTRIES.countryIN,
  'ps': COUNTRIES.countryAF,
  'fa': COUNTRIES.countryIR,
  'pa': COUNTRIES.countryIN,
  'ro': COUNTRIES.countryRO,
  'ru': COUNTRIES.countryRU,
  'gd': COUNTRIES.countryUK,
  'nso': COUNTRIES.countryZA,
  'sr': COUNTRIES.countryCS,
  'sn': COUNTRIES.countryZW,
  'sd': COUNTRIES.countryPK,
  'si': COUNTRIES.countryLK,
  'sk': COUNTRIES.countrySK,
  'sl': COUNTRIES.countrySI,
  'so': COUNTRIES.countrySO,
  'su': COUNTRIES.countryID,
  'sv': COUNTRIES.countrySE,
  'tl': COUNTRIES.countryPH,
  'tg': COUNTRIES.countryTJ,
  'tt': COUNTRIES.countryRU,
  'te': COUNTRIES.countryIN,
  'th': COUNTRIES.countryTH,
  'tr': COUNTRIES.countryTR,
  'tk': COUNTRIES.countryTM,
  'ak': COUNTRIES.countryGH,
  'uk': COUNTRIES.countryUA,
  'uz': COUNTRIES.countryUZ,
  'vi': COUNTRIES.countryVN,
  'cy': COUNTRIES.countryUK,
  'xh': COUNTRIES.countryZA,
  'zu': COUNTRIES.countryZA,
  'la': COUNTRIES.countryUS,
  'zh-CN': COUNTRIES.countryCN,
  'zh-TW': COUNTRIES.countryCN,
  'mni-Mtei': COUNTRIES.countryIN,
  'ta': [COUNTRIES.countryIN, COUNTRIES.countryLK],
  'ti': [COUNTRIES.countryET, COUNTRIES.countryER],
  'ur': [COUNTRIES.countryIN, COUNTRIES.countryPK],
  'ug': [COUNTRIES.countryCN, COUNTRIES.countryKZ],
  'yi': [COUNTRIES.countryUS, COUNTRIES.countryIL],
  'sa': [COUNTRIES.countryUS, COUNTRIES.countryIN],
  'as': [COUNTRIES.countryBT, COUNTRIES.countryIN],
  'bn': [COUNTRIES.countryBD, COUNTRIES.countryIN],
  'ee': [COUNTRIES.countryGH, COUNTRIES.countryTG],
  'rw': [COUNTRIES.countryRW, COUNTRIES.countryBI],
  'ko': [COUNTRIES.countryKR, COUNTRIES.countryKP],
  'om': [COUNTRIES.countryET, COUNTRIES.countryKE],
  'sm': [COUNTRIES.countryWS, COUNTRIES.countryAS],
  'st': [COUNTRIES.countryLS, COUNTRIES.countryZA],
  'sw': [COUNTRIES.countryTZ, COUNTRIES.countryKE, COUNTRIES.countryMZ],
  'yo': [COUNTRIES.countryNG, COUNTRIES.countryBJ, COUNTRIES.countryTG],
  'ay': [COUNTRIES.countryPE, COUNTRIES.countryBO, COUNTRIES.countryCL],
  'ny': [COUNTRIES.countryMW, COUNTRIES.countryZM, COUNTRIES.countryMZ],
  'hmn': [COUNTRIES.countryCN, COUNTRIES.countryVN, COUNTRIES.countryLA],
  'bho': [COUNTRIES.countryIN, COUNTRIES.countryNP, COUNTRIES.countryMU],
  'nl': [COUNTRIES.countryNL, COUNTRIES.countryBE, COUNTRIES.countrySR, COUNTRIES.countryAW],
  'ts': [COUNTRIES.countryMZ, COUNTRIES.countryZA, COUNTRIES.countryZW, COUNTRIES.countrySZ],
  'ar': [
    COUNTRIES.countryDZ, COUNTRIES.countrySA, COUNTRIES.countryBH, COUNTRIES.countryTD,
    COUNTRIES.countryDJ, COUNTRIES.countryEG, COUNTRIES.countryER, COUNTRIES.countryIQ,
    COUNTRIES.countryYE, COUNTRIES.countryJO, COUNTRIES.countryQA, COUNTRIES.countryKM,
    COUNTRIES.countryKW, COUNTRIES.countryLB, COUNTRIES.countryMA, COUNTRIES.countryMR,
    COUNTRIES.countryOM, COUNTRIES.countryPS, COUNTRIES.countrySO, COUNTRIES.countrySD,
    COUNTRIES.countrySY, COUNTRIES.countryTN, COUNTRIES.countryAE
  ],
  'en': [
    COUNTRIES.countryUK, COUNTRIES.countryUS, COUNTRIES.countryCA, COUNTRIES.countryAU,
    COUNTRIES.countryIE, COUNTRIES.countryGI, COUNTRIES.countryAI, COUNTRIES.countryAG,
    COUNTRIES.countryBS, COUNTRIES.countryBB, COUNTRIES.countryBZ, COUNTRIES.countryBM,
    COUNTRIES.countryKY, COUNTRIES.countryDM, COUNTRIES.countryGD, COUNTRIES.countryJM,
    COUNTRIES.countryMS, COUNTRIES.countryPR, COUNTRIES.countryKN, COUNTRIES.countryLC,
    COUNTRIES.countryVC, COUNTRIES.countryTT, COUNTRIES.countryTC, COUNTRIES.countryFK,
    COUNTRIES.countryGF, COUNTRIES.countryMT, COUNTRIES.countryBW, COUNTRIES.countryCM,
    COUNTRIES.countrySZ, COUNTRIES.countryGM, COUNTRIES.countryGH, COUNTRIES.countryKE,
    COUNTRIES.countryLS, COUNTRIES.countryLR, COUNTRIES.countryMW, COUNTRIES.countryMU,
    COUNTRIES.countryNA, COUNTRIES.countryNG, COUNTRIES.countryRW, COUNTRIES.countrySH,
    COUNTRIES.countrySL, COUNTRIES.countryZA, COUNTRIES.countrySD, COUNTRIES.countryTZ,
    COUNTRIES.countryUG, COUNTRIES.countryZM, COUNTRIES.countryZW, COUNTRIES.countryCX,
    COUNTRIES.countryCC, COUNTRIES.countryHK, COUNTRIES.countryIN, COUNTRIES.countryPK,
    COUNTRIES.countryPH, COUNTRIES.countrySG, COUNTRIES.countryAS, COUNTRIES.countryCK,
    COUNTRIES.countryFJ, COUNTRIES.countryGU, COUNTRIES.countryKI, COUNTRIES.countryMH,
    COUNTRIES.countryFM, COUNTRIES.countryNR, COUNTRIES.countryNZ, COUNTRIES.countryNU,
    COUNTRIES.countryNF, COUNTRIES.countryMP, COUNTRIES.countryPW, COUNTRIES.countryPG,
    COUNTRIES.countryPN, COUNTRIES.countryWS, COUNTRIES.countrySB, COUNTRIES.countryTK,
    COUNTRIES.countryTV, COUNTRIES.countryVU
  ],
  'fr': [
    COUNTRIES.countryDZ, COUNTRIES.countryAD, COUNTRIES.countryBE, COUNTRIES.countryBJ,
    COUNTRIES.countryBF, COUNTRIES.countryBI, COUNTRIES.countryTD, COUNTRIES.countryGH,
    COUNTRIES.countryDJ, COUNTRIES.countryFR, COUNTRIES.countryGA, COUNTRIES.countryGQ,
    COUNTRIES.countryGN, COUNTRIES.countryHT, COUNTRIES.countryCM, COUNTRIES.countryCA,
    COUNTRIES.countryKM, COUNTRIES.countryCG, COUNTRIES.countryLA, COUNTRIES.countryLB,
    COUNTRIES.countryLU, COUNTRIES.countryMG, COUNTRIES.countryMA, COUNTRIES.countryMR,
    COUNTRIES.countryMU, COUNTRIES.countryMC, COUNTRIES.countryNE, COUNTRIES.countryCF,
    COUNTRIES.countryRW, COUNTRIES.countrySN, COUNTRIES.countrySC, COUNTRIES.countryCH,
    COUNTRIES.countryTG, COUNTRIES.countryTT, COUNTRIES.countryTN, COUNTRIES.countryVU,
    COUNTRIES.countryCI
  ],
  'ku': [
    COUNTRIES.countryIQ, COUNTRIES.countryTN, COUNTRIES.countryIR, COUNTRIES.countrySY,
    COUNTRIES.countryAM
  ],
  'ms': [
    COUNTRIES.countryID, COUNTRIES.countryMY, COUNTRIES.countryTH, COUNTRIES.countryBN,
    COUNTRIES.countrySG
  ],
  'pt': [
    COUNTRIES.countryAO, COUNTRIES.countryBR, COUNTRIES.countryGW, COUNTRIES.countryGQ,
    COUNTRIES.countryMZ, COUNTRIES.countryPT, COUNTRIES.countryCV, COUNTRIES.countryTP,
    COUNTRIES.countryMO
  ],
  'qu': [
    COUNTRIES.countryAR, COUNTRIES.countryEC, COUNTRIES.countryCO, COUNTRIES.countryPE,
    COUNTRIES.countryBO
  ],
  'es': [
    COUNTRIES.countryAR, COUNTRIES.countryBO, COUNTRIES.countryCL, COUNTRIES.countryDO,
    COUNTRIES.countryEC, COUNTRIES.countryGT, COUNTRIES.countryGQ, COUNTRIES.countryES,
    COUNTRIES.countryHN, COUNTRIES.countryCO, COUNTRIES.countryRW, COUNTRIES.countryCU,
    COUNTRIES.countryMX, COUNTRIES.countryNI, COUNTRIES.countryPA, COUNTRIES.countryPY,
    COUNTRIES.countryPE, COUNTRIES.countrySV, COUNTRIES.countryUY, COUNTRIES.countryVE,
    COUNTRIES.countryUS, COUNTRIES.countryFI
  ],
};
