micronaut:
  application:
    name: poliglotek
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_SECRET}"
  server:
    host: 0.0.0.0 # https://chatgpt.com/share/67e5ac48-0b6c-8008-81b8-c8a3d93a175e
    port: 8080
    cors:
      enabled: true
      configurations:
        default:
          allowed-origins:
            - http://localhost:4200
            - http://localhost:8080
            - https://www.poliglotek.com
          allowed-methods:
            - POST
            - GET
            - PUT
            - DELETE
            - OPTIONS
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public/browser

http:
  client:
    read-timeout: 30s

netty:
  default:
    allocator:
      max-order: 3

gcp:
  firestore:
    project-id: "${GOOGLE_CLOUD_PROJECT_ID}"

google-cloud:
  translation:
    project-id: "${GOOGLE_CLOUD_PROJECT_ID}"
  search:
    api-key: "${GOOGLE_CUSTOM_SEARCH_API_KEY}"
    engine-id: "${GOOGLE_CUSTOM_SEARCH_ENGINE_ID}"
    limit: 4
  oauth:
    client-id: "${OAUTH_CLIENT_ID}"

mailgun-api-key: "${MAILGUN_API_KEY}" # TODO: needs to be changed to kebab-case in the branch where it's used

akismet:
  api-key: "${AKISMET_API_KEY}" # TODO: needs to be changed to kebab-case in the branch where it's used
