micronaut:
  application:
    name: poliglotek
  server:
    cors:
      enabled: true
      configurations:
        default:
          allowedOrigins: ["http://localhost:4200"]
          allwedMethods:
            - POST
            - GET
            - PUT
            - DELETE
            - OPTIONS
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public/browser

http:
  client:
    read-timeout: 30s

netty:
  default:
    allocator:
      max-order: 3

googleCloud:
  projectId: ${googleCloudProjectId}
  customSearchApiKey: ${googleCustomSearchApiKey}
  customSearchEngineId: ${googleCustomSearchEngineId}

mailguApiKey: ${mailgunApiKey}

akismet:
  apiKey: ${akismetApiKey}
