#!/bin/bash

# Commands this script is executed with:
# 1. `bash podman-build -i <environment_type>`. Environment type must be `dev` or `prod`
# 2. `bash podman-build -c <image_id>. `image_id` is obtained beforehand with command `podman images`
# 3. `bash podman-build -t <image_name_with_tag>
# podman tag poliglotek:0.48.38-792b046 europe-west2-docker.pkg.dev/translation-to-polish-437813/poliglotek/poliglotek:0.48.38-792b046
# podman push europe-west2-docker.pkg.dev/translation-to-polish-437813/poliglotek/poliglotek:0.48.38-792b046

# Exit on error, undefined variable, or pipe failure
set -euo pipefail

# Create an array with shell constants which must be set in bashrc before running the script
PREDEFINED_SHELL_CONSTANTS=(POLIGLOTEK_PROJECT_ROOT GOOGLE_CREDS_FILE_NAME ENV_VARS_FILE_PATH EXPOSED_PORT)

# Flag to track if all constants are set
all_constants_set=true

# Validate shell predefined constants. If any of them is not set do not continue.
for constant in "${PREDEFINED_SHELL_CONSTANTS[@]}"; do
    if [[ -z "${!constant}" ]]; then  # Use indirect expansion to check the value of the variable
        echo "Error: The required constant '$constant' is not set"
        all_constants_set=false
    fi
done

if [[ "$all_constants_set" = false ]]; then
    echo "Please set the missing constants in your bashrc and try again."
    echo " Required constants are: ${PREDEFINED_SHELL_CONSTANTS[*]}"
    exit 1
fi

# Other constants
DOCKERFILE_PATH="$POLIGLOTEK_PROJECT_ROOT/Dockerfile"
APP_NAME="poliglotek"
VALID_ENVIRONMENT_TYPES=("dev" "prod")
G_CLOUD_REGION="europe-west2-docker.pkg.dev"
G_CLOUD_PROJECT_ID="translation-to-polish-437813"


check_dependencies() {
    for cmd in podman git; do
        command -v "$cmd" >/dev/null 2>&1 || { echo "Error: $cmd is not installed."; exit 1; }
    done
}

# Retrieves application version from build.gradle
get_app_version() {
    (cd "$POLIGLOTEK_PROJECT_ROOT" && ./gradlew -q properties | grep "^version:" | sed 's/version: *//g')
}

get_commit_id() {
    git rev-parse --short HEAD
}

get_git_branch_name() {
    git rev-parse --abbrev-ref HEAD
}

# Retrieves Podman image tag to use it later in container name for easier identification
# Image tag is retrieved using image id passed from the cli as an argument
get_image_tag() {
    local image_id="$1" # To get image id use command `podman images` before running this script
    podman images --filter "id=$image_id" --format "{{.Tag}}" || true
}

get_image_name_with_tag() {
    local image_id="$1"
    podman images --filter "id=$image_id" --format "{{.Repository}}:{{.Tag}}"
}

usage() {
    echo "Usage: $0 <flag> <arg> [image_id]"
    echo
    echo "Flags:"
    echo "  -i, --image       Build a Podman image"
    echo "  -c, --container   Run a Podman container"
    echo "  -t, --tag         Tag image before pushing to registry"
    echo "  -p, --push        Push image to registry"
    echo
    echo "Env:"
    echo "  dev, prod         Mandatory environment specifier for image build"
    echo
    echo "Examples:"
    echo "  Build an image: $0 -i dev"
    echo "  Run a container: $0 -c <image_id>"
    echo "  Tag image before pushing it to registry: $0 -t <image_id>"
    exit 1
}

# Validate input arguments
# There must be two: `-i <environment_name>` or `-c <image_id>`
if [[ "$#" -lt 2 ]]; then
    usage
fi

check_dependencies

flag="$1"
arg="$2"

case $flag in
    -i|--image)
    # Validate mandatory environment types for image build
    # Environment type is passed from the cli as an argument
    environment="${arg}"
    if [[ ! " ${VALID_ENVIRONMENT_TYPES[*]} " =~ ${environment} ]]; then
        echo "Error: Invalid environment. Valid options are: ${VALID_ENVIRONMENT_TYPES[*]}"
        usage
    fi

    # Generate image name
    IMAGE_NAME="${APP_NAME}-img"
    BRANCH=$(get_git_branch_name) # Branch whose name is used must be checked out when running this script
    COMMIT_ID=$(get_commit_id)
    APP_VERSION=$(get_app_version)
    IMAGE_TAG="${environment}-${BRANCH}-${COMMIT_ID}-${APP_VERSION}"
    IMAGE_NAME_WITH_TAG="${IMAGE_NAME}:${IMAGE_TAG}"

    # Build image and validate success
    echo "Building Podman image: $IMAGE_NAME_WITH_TAG"
    if podman build -t "$IMAGE_NAME_WITH_TAG" -f "$DOCKERFILE_PATH"; then
        echo "Image built successfully: $IMAGE_NAME_WITH_TAG"
    else
        echo "Error: Failed to build image"
        exit 1
    fi
    ;;
    -c|--container)
    image_id="$arg"
    image_tag=$(get_image_tag "$image_id")
    if [[ -z "$image_tag" ]]; then
        echo "Error: Image with ID '$image_id' not found"
        exit 1
    fi
    container_name="${APP_NAME}-${image_tag}"
    echo "Running Podman container: $container_name"

    # Build container and validate success
    if podman run --name "$container_name" -it --secret "$GOOGLE_CREDS_FILE_NAME",type=mount \
        --arg-file "$ENV_VARS_FILE_PATH" -p "$EXPOSED_PORT" "$image_id"; then
        echo "Container created successfully: $container_name"
    else
        echo "Error: Failed to create container"
        exit 1
    fi
    ;;
    -t|--tag)
    image_id="$arg"
    image_name_with_tag=$(get_image_name_with_tag "$image_id")
    if [[ -z "$image_name_with_tag" ]]; then
        echo "Error: Image with ID '$image_id' not found"
        exit 1
    fi
    if podman tag "$image_name_with_tag" "$G_CLOUD_REGION"/"$G_CLOUD_PROJECT_ID"\
        /"${APP_NAME}"/"$image_name_with_tag"; then # APP_NAME is repo name in registry
        echo "Image $image_name_with_tag tagged for pushing to registry successfully"
    else
        echo "Error: Failed to tag image $image_name_with_tag for pushing to registry"
        exit 1
    fi
    ;;
    -p|--push)
    image_id="$arg"
    image_name_with_tag=$(get_image_name_with_tag "$image_id")
    if [[ -z "$image_name_with_tag" ]]; then
            echo "Error: Image with ID '$image_id' not found"
            exit 1
    fi
    if podman push "$G_CLOUD_REGION"/"$G_CLOUD_PROJECT_ID"/"${APP_NAME}"/"$image_name_with_tag"; then
        echo "Image $image_name_with_tag pushed to registry successfully "
    else
        echo "Error: Failed to push image $image_name_with_tag to registry"
    fi
    ;;
*)
    echo "Unknown flag: $flag"
    usage
    ;;
esac